version: "3.9"

services:
  unittest:
    container_name: aws-api-demo-test
    build:
      dockerfile: Dockerfile.Api
      context: .
    entrypoint: poetry run pytest
  api:
    platform: linux/arm64
    container_name: aws-api-demo
    image: ${ECR_REPO_BASE_URL}/api
    build:
      dockerfile: Dockerfile.Api
      context: .
    ports:
      - "9000:8080"
